image: "timbru31/java-node:11-14"

# Test
stages:
  - prepare
  - beta
  - prod

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - build/
    - .docusaurus/

before_script:
  - yarn install

build:
  stage: prepare
  script:
    - yarn build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - mainline
  resource_group: build-step

deploy-beta:
  stage: beta
  script:
    - yarn deploy:beta
  environment:
    name: beta
    url: https://whylabs-docs-dev.netlify.app/
  dependencies:
    - build
  only:
    - mainline
  resource_group: beta

deploy-prod:
  stage: prod
  script:
    - yarn deploy:prod
  environment:
    name: prod
    url: https://docs.whylabs.ai
  when: manual
  only:
    - mainline
  resource_group: prod
  artifacts:
    paths:
      - build
    expire_in: 1 month

deploy-preview:
  stage: beta
  script:
    - yarn deploy:preview
  only:
    - merge_requests
